repos:
-   repo: local
    hooks:
    -   id: flake8
        name: flake8
        entry: just flake8
        language: system
        types_or: [python, flake8]
    -   id: black
        name: black
        entry: just black
        language: system
        files: (^pyproject\.toml|\.py)$
    -   id: isort
        name: isort
        entry: just isort
        language: system
        files: (^pyproject\.toml|\.py)$
    -   id: safety
        name: safety
        entry: just safety
        language: system
        files: poetry.lock
    -   id: newline-check
        name: check files have final newlines
        entry: just newline-check
        language: system
    -   id: test
        name: test
        entry: just test
        language: system
        files: (^pytest\.ini|^\.coveragerc|\.py)$
    -   id: bandit
        name: bandit
        entry: just bandit
        language: system
        files: (^\.bandit|^src\/.+\.py)$
